app = "wireguard-shy-firefly-4959"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

# Add secrets for WireGuard private key:
# fly secrets set WIREGUARD_PRIVATE_KEY="your_private_key_here"

[vm]
  # Grant necessary capabilities for WireGuard
  cpu_kind = "shared"
  cpu_count = 1
  memory_mb = 256

# WireGuard Service (UDP)
[[services]]
  internal_port = 51820
  protocol = "udp"

  [[services.ports]]
    port = 51820

# API Service (TCP)
[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 5000
