const Client = require("../models/Client");
const {
    wgLock,
    log,
    KEEPALIVE_TIME,
    validateKeepalive,
    runWgCommand,
    getServerPublicKey,
    getServerEndpoint
} = require("../wg-core");
const {
    generateKeys,
    getNextAvailableIP,
    ensureClientRecord
} = require("../utils/route-helpers");

// Register all MikroTik-related routes
function registerMikrotikRoutes(app, getDbInitialized) {
    // Generate a MikroTik RouterOS script that auto-configures WireGuard and tests connectivity
    app.post("/generate-mikrotik", async (req, res) => {
        try {
            const { name, notes, interfaceName, allowedSubnet } = req.body || {};

            if (!name) {
                return res.status(400).json({
                    success: false,
                    error: "Name is required. Please provide a name for the MikroTik client."
                });
            }

            const clientName = name.toLowerCase().trim();

            // 1) Generate client keys
            const { privateKey, publicKey } = await generateKeys();

            // 2) Allocate IP (stored as /32)
            const allocatedIpWithCidr = await getNextAvailableIP(getDbInitialized()); // e.g. 10.0.0.7/32
            const allocatedIp = allocatedIpWithCidr.split("/")[0];

            // 3) Persist to DB
            const client = new Client({
                name: clientName,
                ip: allocatedIpWithCidr,
                publicKey,
                privateKey,
                enabled: true,
                notes: notes || ''
            });
            try {
                await client.save();
            } catch (err) {
                if (err && err.code === 11000) {
                    return res.status(409).json({
                        success: false,
                        error: "Client with this name already exists",
                        field: Object.keys(err.keyPattern || { name: 'name' })[0]
                    });
                }
                throw err;
            }

            // 4) Add to running WireGuard
            try {
                await wgLock.run(() => runWgCommand(['set', 'wg0', 'peer', publicKey, 'allowed-ips', allocatedIpWithCidr, 'persistent-keepalive', String(KEEPALIVE_TIME)]));
            } catch (error) {
                // Proceed even if wg0 is not yet up; DB has the record
                log('warn', 'peer_add_failed', { client: clientName, error: error?.message || String(error) });
            }

            // 5) Build MikroTik script
            const serverPublicKey = (await getServerPublicKey()).trim();
            const serverEndpoint = getServerEndpoint(); // expected format: host:port
            const iface = (interfaceName || `wireguard-${clientName}`).replace(/[^a-zA-Z0-9_-]/g, '-');
            const allowed = allowedSubnet || "10.0.0.0/24";

            // RouterOS script (safe to paste as one-shot)
            const serverEndpointParts = serverEndpoint.split(':');
            const serverHost = serverEndpointParts[0];
            const serverPort = serverEndpointParts[1] || '51820';
            
            const mikrotikScript = `# Auto-generated by WireGuard API for client: ${clientName}\r\n` +
`# Creates WG interface, sets keys/IP, peer, route, then tests connectivity\r\n` +
`:local IFACE "${iface}"\r\n` +
`:local CLIENT_IP "${allocatedIpWithCidr}"\r\n` +
`:local SERVER_PUBKEY "${serverPublicKey}"\r\n` +
`:local SERVER_HOST "${serverHost}"\r\n` +
`:local SERVER_PORT "${serverPort}"\r\n` +
`:local ALLOWED_SUBNET "${allowed}"\r\n` +
`:local KEEPALIVE 25\r\n` +
`:local SERVER_WG_IP "10.0.0.1"\r\n` +
`` +
`# 1) Create interface if missing\r\n` +
`:if ([/interface wireguard print count-only where name=$IFACE] = 0) do={\r\n` +
`  /interface wireguard add name=$IFACE;\r\n` +
`  :put "Created WireGuard interface: $IFACE";\r\n` +
`} else={\r\n` +
`  :put "WireGuard interface $IFACE already exists";\r\n` +
`}\r\n` +
`# 2) Set private key\r\n` +
`/interface wireguard set [find where name=$IFACE] private-key=\"${privateKey}\";\r\n` +
`:put "Set private key for $IFACE";\r\n` +
`# 3) Assign tunnel address (only if not already assigned)\r\n` +
`:if ([/ip address print count-only where address=$CLIENT_IP] = 0) do={\r\n` +
`  /ip address add address=$CLIENT_IP interface=$IFACE disabled=no;\r\n` +
`  :put "Assigned IP address $CLIENT_IP to $IFACE";\r\n` +
`} else={\r\n` +
`  :put "IP address $CLIENT_IP already assigned";\r\n` +
`}\r\n` +
`# 4) Add or update peer (server)\r\n` +
`:local PEER_ID [/interface wireguard peers find where interface=$IFACE public-key=$SERVER_PUBKEY];\r\n` +
`:if ([:len $PEER_ID] = 0) do={\r\n` +
`  /interface wireguard peers add interface=$IFACE public-key=$SERVER_PUBKEY endpoint-address=$SERVER_HOST endpoint-port=$SERVER_PORT allowed-address=$ALLOWED_SUBNET persistent-keepalive=$KEEPALIVE;\r\n` +
`  :put "Added peer (server) to $IFACE";\r\n` +
`} else={\r\n` +
`  /interface wireguard peers set $PEER_ID endpoint-address=$SERVER_HOST endpoint-port=$SERVER_PORT allowed-address=$ALLOWED_SUBNET persistent-keepalive=$KEEPALIVE;\r\n` +
`  :put "Updated peer (server) on $IFACE";\r\n` +
`}\r\n` +
`# 5) Ensure route to allowed subnet via WG (only if not exists)\r\n` +
`:if ([/ip route print count-only where dst-address=$ALLOWED_SUBNET gateway=$IFACE] = 0) do={\r\n` +
`  /ip route add dst-address=$ALLOWED_SUBNET gateway=$IFACE disabled=no;\r\n` +
`  :put "Added route to $ALLOWED_SUBNET via $IFACE";\r\n` +
`} else={\r\n` +
`  :put "Route to $ALLOWED_SUBNET via $IFACE already exists";\r\n` +
`}\r\n` +
`# 6) Enable interface if disabled\r\n` +
`/interface wireguard enable [find where name=$IFACE];\r\n` +
`:put "Enabled interface $IFACE";\r\n` +
`# 7) Test connectivity to server WG IP\r\n` +
`:delay 2;\r\n` +
`:local success 0;\r\n` +
`:do {\r\n` +
`  /ping $SERVER_WG_IP count=3;\r\n` +
`  :set success 1;\r\n` +
`} on-error={ :set success 0; };\r\n` +
`# 8) Report\r\n` +
`:if ($success = 1) do={ :put \"✅ WG setup OK for ${clientName}. Ping to $SERVER_WG_IP succeeded.\" } else={ :put \"⚠️ WG setup completed but ping to $SERVER_WG_IP failed. Check firewall/connectivity.\" };\r\n`;

            res.setHeader('Content-Type', 'text/plain');
            res.setHeader('Content-Disposition', `attachment; filename="${clientName}.rsc"`);
            return res.send(mikrotikScript);
        } catch (error) {
            log('error', 'generate_mikrotik_error', { error: error.message });
            return res.status(500).json({
                success: false,
                error: "Failed to generate MikroTik configuration script",
                details: error.message
            });
        }
    });

    // Compact MikroTik script via short URL: GET /mt/:name
    // - Finds or creates client, then returns a minified RouterOS script
    // - Script auto-picks an available listen-port starting at 51810
    app.get("/mt/:name", async (req, res) => {
        try {
            const { name } = req.params;
            const { notes, iface, subnet } = req.query;

            if (!name) {
                return res.status(400).json({ success: false, error: "Missing name" });
            }

            const client = await ensureClientRecord({ name, notes, interfaceName: iface }, getDbInitialized());
            const serverPublicKey = (await getServerPublicKey()).trim();
            const serverEndpoint = client.endpoint || getServerEndpoint();

            const ifaceName = (client.interfaceName || `wireguard-${client.name}`).replace(/[^a-zA-Z0-9_-]/g, '-');
            const allowed = (subnet || "10.0.0.0/24").toString();
            const addr = client.ip; // /32
            const pKey = client.privateKey;

            // Minified RouterOS script (no comments) - improved with interface enable
            const serverEndpointParts = serverEndpoint.split(':');
            const serverHost = serverEndpointParts[0];
            const serverPort = serverEndpointParts[1] || '51820';
            const s = `:local IFACE "${ifaceName}";:local PRIV "${pKey}";:local IP "${addr}";:local SPK "${serverPublicKey}";:local HOST "${serverHost}";:local PORT "${serverPort}";:local ALLOW "${allowed}";:local LP 51810;:for i from=0 to=32 do={:local T ($LP+$i);:if ([/interface wireguard print count-only where listen-port=$T]=0) do={:set LP $T;:set i 33}};:if ([/interface wireguard print count-only where name=$IFACE]=0) do={/interface wireguard add name=$IFACE};/interface wireguard set [find where name=$IFACE] private-key=$PRIV listen-port=$LP;/interface wireguard enable [find where name=$IFACE];:if ([/ip address print count-only where address=$IP]=0) do={/ip address add address=$IP interface=$IFACE disabled=no};:local PID [/interface wireguard peers find where interface=$IFACE public-key=$SPK];:if ([:len $PID]=0) do={/interface wireguard peers add interface=$IFACE public-key=$SPK endpoint-address=$HOST endpoint-port=$PORT allowed-address=$ALLOW persistent-keepalive=25} else={/interface wireguard peers set $PID endpoint-address=$HOST endpoint-port=$PORT allowed-address=$ALLOW persistent-keepalive=25};:if ([/ip route print count-only where dst-address=$ALLOW gateway=$IFACE]=0) do={/ip route add dst-address=$ALLOW gateway=$IFACE disabled=no};:delay 2;:local ok 0;:do {/ping 10.0.0.1 count=3;:set ok 1} on-error={:set ok 0};:if ($ok=1) do={:put "OK ${name} $IFACE $IP $LP"} else={:put "FAIL ${name}"}`;

            res.setHeader('Content-Type', 'text/plain');
            res.setHeader('Cache-Control', 'no-store');
            return res.send(s);
        } catch (error) {
            log('error', 'mt_shorturl_error', { error: error.message });
            return res.status(500).json({ success: false, error: error.message });
        }
    });

    // MikroTik Auto-Configure (Direct URL)
    app.get("/:name/configure", async (req, res) => {
        try {
            const { name } = req.params;
            const client = await Client.findOne({ name: name.toLowerCase() });
            
            if (!client) {
                return res.status(404).send(`Client "${name}" not found`);
            }
            
            const serverPublicKey = (await getServerPublicKey()).trim();
            const serverEndpoint = client.endpoint || getServerEndpoint();
            const serverEndpointParts = serverEndpoint.split(':');
            const serverHost = serverEndpointParts[0];
            const serverPort = serverEndpointParts[1] || '51820';
            
            const ifaceName = (client.interfaceName || `wireguard-${client.name}`).replace(/[^a-zA-Z0-9_-]/g, '-');
            const allowed = client.allowedIPs || "10.0.0.0/24";
            const keepalive = validateKeepalive(client.persistentKeepalive);
            
            // Generate minified MikroTik script (single line, no comments) - same format as working script
            // This format works when fetched via /tool/fetch and imported
            const autoconfigScript = `:local IFACE "${ifaceName}";:local PRIV "${client.privateKey}";:local IP "${client.ip}";:local SPK "${serverPublicKey}";:local HOST "${serverHost}";:local PORT "${serverPort}";:local ALLOW "${allowed}";:local LP 51810;:for i from=0 to=32 do={:local T ($LP+$i);:if ([/interface wireguard print count-only where listen-port=$T]=0) do={:set LP $T;:set i 33}};:if ([/interface wireguard print count-only where name=$IFACE]=0) do={/interface wireguard add name=$IFACE};/interface wireguard set [find where name=$IFACE] private-key=$PRIV listen-port=$LP;/interface wireguard enable [find where name=$IFACE];:if ([/ip address print count-only where address=$IP]=0) do={/ip address add address=$IP interface=$IFACE disabled=no};:local PID [/interface wireguard peers find where interface=$IFACE public-key=$SPK];:if ([:len $PID]=0) do={/interface wireguard peers add interface=$IFACE public-key=$SPK endpoint-address=$HOST endpoint-port=$PORT allowed-address=$ALLOW persistent-keepalive=${keepalive}} else={/interface wireguard peers set $PID endpoint-address=$HOST endpoint-port=$PORT allowed-address=$ALLOW persistent-keepalive=${keepalive}};:if ([/ip route print count-only where dst-address=$ALLOW gateway=$IFACE]=0) do={/ip route add dst-address=$ALLOW gateway=$IFACE disabled=no};:delay 2;:local ok 0;:do {/ping 10.0.0.1 count=3;:set ok 1} on-error={:set ok 0};:if ($ok=1) do={:put "OK ${client.name} $IFACE $IP $LP"} else={:put "FAIL ${client.name}"}`;
            
            res.setHeader('Content-Type', 'text/plain');
            res.setHeader('Content-Disposition', `attachment; filename="${client.name}-autoconfig.rsc"`);
            res.send(autoconfigScript);
        } catch (error) {
            log('error', 'autoconfig_error', { name: req.params.name, error: error.message });
            res.status(500).send("Failed to generate auto-config script");
        }
    });
}

module.exports = registerMikrotikRoutes;
